### ISSUE TITLE
AttributeError: 'list' object has no attribute 'items'

### ISSUE THREAD

**Issue by exisz** [claytondaley/drf-keyed-list#2]
Oops, I think something is probs broken. I am using python 3.7 and django 2.15.

Following prescription, I am just doing this:
a = UserSerializer(User.objects.all(), many=True).data

```bash
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "C:\Users\e\.virtualenvs\pinx-atTbH4Fl\lib\site-packages\rest_framework\serializers.py", line 765, in data
    ret = super(ListSerializer, self).data
  File "C:\Users\e\.virtualenvs\pinx-atTbH4Fl\lib\site-packages\rest_framework\serializers.py", line 262, in data
    self._data = self.to_representation(self.instance)
  File "C:\Users\e\.virtualenvs\pinx-atTbH4Fl\lib\site-packages\drf_keyed_list\serializers.py", line 19, in to_representation
    return {v.pop(self._keyed_field): v for k, v in response.items()}
AttributeError: 'list' object has no attribute 'items'
```

It seems that `.items()` is a dict method however the serializer is returning a list. I think it's a minor problem, but just haven't figure out how to modify the code...

**Comment by claytondaley** [comment]
Can you show me your code?

**Comment by claytondaley** [comment]
I can look into this if you can show me an extract of the class where you're using it.

**Comment by sshishov** [comment]
Same error here. It seems that something is wrong.

Omission in the docs: not specified what kind of format accepted as data:
```python
data = {
  'id_value' : {
    ...  # data
  }
}
```
or 
```python
data = [
  {
    'id': 'id_value',
    ...  # data
  }
]
```
I tried both and for both I got exceptions.
For the first example:
```python
return {v.pop(self._keyed_field): v for k, v in response.items()}  # <-- this line
Exception Value: 'list' object has no attribute 'items'
```
Second:
```python
data = [{**v, **{self._keyed_field: k}} for k, v in data.items()]  # <-- this line
Exception Value: 'list' object has no attribute 'items'
```

**Comment by sshishov** [comment]
I found originally your answer here: https://stackoverflow.com/a/53548818
Please check how you do handle `to_representation` there... You iterate over list and in your repo you iterate over dict...
--- Updates
Also no validation is provided. If you pass incorrect type then you get unhandled exception. I guess that some validation should be added there to handle these edge cases.
